django-excel-print-versionx/ExcelApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'ExcelApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/$', views.details, name='details'),
    #url(r'^details/(?P<pid>[0-9]+)/$', views.getReport, name='getReport'),
    url(r'^getReport/$', views.getReport, name='getReport'),
    #url(r'^ExcelApp/$', views.details, name='details'),
]

django-excel-print-versionx/PythonOfficePrint/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^ExcelApp/', include('ExcelApp.urls')),
    url(r'^admin/', admin.site.urls),
]

django-excel-print-versionx/ExcelApp/models.py
from django.db import models

django-excel-print-versionx/ExcelApp/views.py
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse
from django.http import JsonResponse
import requests
from . import rgen

#Dictionary mapping report id to restful API
d = {'2' : 'http://ykr-dev-apex.devyork.ca/apexenv/bsmart_data/bsmart_data/stp_ws/stp_pop_test/', '18' : 'http://ykr-dev-apex.devyork.ca/apexenv/bsmart_data/bsmart_data/stp_ws/stp_nusery_inspection_test/'}



#index page for gui
def index(request):
	return render(request, 'ExcelApp/index.html')

#main page for filling the form
def details(request):
	return render(request, 'ExcelApp/main.html')

#returns json for testing
def getReport(request):
	#report id
	rid = request.POST['rid']

	#if the id is in the dictionary
	if rid in d:
		response = requests.get(d[rid])

		#rgen.report.formExcel(response.content.decode("utf-8"), rid) # added decode
		rgen.report.formExcel(response.content, rid) 
		file = HttpResponse(response, mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
		file['Content-Disposition'] = "attachment; filename=test.xlsx"

		#displays the json
		return HttpResponse(file)
	else:
		return HttpResponse('No API in Dictionary')

django-excel-print-versionx/ExcelApp/templates/ExcelApp/index.html
<h1>Excel Office Print</h1>
<a href="{% url 'ExcelApp:details' %}">To Excel App</a>

django-excel-print-versionx/ExcelApp/templates/ExcelApp/main.html
<html>
	<body>
		<form action="{% url 'ExcelApp:getReport' %}" method="POST">
		{% csrf_token %}
			<p><label for="rid">Report ID:</label>   
			<input type="text" name="rid" id="rid"></input></p>
			<button type="submit" value="item">get report</button>
		</form>
	</body>
</html>

django-excel-print-versionx/ExcelApp/templates/ExcelApp/test.html
<h1 style="color: blue">This is a test</h1>